### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by cedias** [plotly/plotly.py#104]
Hi,
when I try to run this classic api example:

``` python
import plotly.plotly as py
from plotly.graph_objs import *

py.sign_in("myusername", "mykey")

data = Data([
    Bar(
        x=['giraffes', 'orangutans', 'monkeys'],
        y=[20, 14, 23]
    )
])

plot_url = py.plot(data, filename='basic-bar')
```

I get this error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import plotly.plotly as py
  File "/usr/local/lib/python2.7/dist-packages/plotly/__init__.py", line 31, in <module>
    from plotly import plotly, graph_objs, tools, utils
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/__init__.py", line 12, in <module>
    from plotly.plotly.plotly import *
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 29, in <module>
    from plotly import tools
  File "/usr/local/lib/python2.7/dist-packages/plotly/tools.py", line 20, in <module>
    from . graph_objs import graph_objs
  File "/usr/local/lib/python2.7/dist-packages/plotly/graph_objs/__init__.py", line 12, in <module>
    from plotly.graph_objs.graph_objs import *
  File "/usr/local/lib/python2.7/dist-packages/plotly/graph_objs/graph_objs.py", line 281, in <module>
    @six.add_metaclass(ListMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
```

i'm on linux mint 16 - Python 2.7.5+ 
Any clues ?

**Comment by nees2012** [comment]
Hi i am new to using mac and trying to install plotly on mac using python 2.7.
pip install plotly (worked)
pip install --upgrade plotly (worked)
 Still i am getting import error as follows:
>>> import plotly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named plotly
>>> 
thanks for help.

**Comment by Tui-yy** [comment]
same issue as nees2012

**Comment by Moonmun** [comment]
facing the same issue., upgrade command does no help

**Comment by shanurrahman** [comment]
upgrade helped me
