### ISSUE TITLE
Tutorial doesn't work on first line

### ISSUE THREAD

**Issue by creidieki** [plotly/plotly.py#1049]
I tried following along with the tutorial at https://plot.ly/python/plot-data-from-csv/   but when I pasted the In[3] line into a python file and ran it, it didn't output a table, it gave me an error message:

Aw, snap! We didn't get a username with your request.

Don't have an account? https://plot.ly/api_signup

Questions? accounts@plot.ly
Traceback (most recent call last):
  File "plot.py", line 11, in <module>
    py.iplot(sample_data_table, filename='sample-data-table')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plotly/plotly/plotly.py", line 173, in iplot
    return tools.embed(url, **embed_options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plotly/tools.py", line 395, in embed
    return PlotlyDisplay(url, width, height)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plotly/tools.py", line 1442, in __init__
    self.embed_code = get_embed(url, width=width, height=height)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plotly/tools.py", line 300, in get_embed
    "".format(url, plotly_rest_url))
plotly.exceptions.PlotlyError: Because you didn't supply a 'file_id' in the call, we're assuming you're trying to snag a figure from a url. You supplied the url, '', we expected it to start with 'https://plot.ly'.
Run help on this function for more information.

That error message doesn't even make sense, I'm doing a tutorial offline. Please fix the tutorial.

**Comment by jonmmease** [comment]
Hi @creidieki , thanks for letting us know. Would you mind moving this issue to the documentation repo at https://github.com/plotly/documentation/issues?
Thanks!
