### ISSUE TITLE
OpenSSL.SSL.SysCallError raised when loading huge matrix (1000 X 22977) to create a heatmap

### ISSUE THREAD

**Issue by raphael-upmc** [plotly/plotly.py#1494]
Hi there,

I'm using Plot.ly and Dash, I would like to say that both are a super cool tools! I use them in order to create interactive heatmaps and it used to work very well with a binary matrice of ~2700 rows and ~900 columns. However, I get errors with a larger matrix (1000 row and 22000 columns). Looks like the matrix is too large. Is there a way to deal with such a large matrix ?

Best,

Raphael

below is the errors raised:

```
Traceback (most recent call last):
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 304, in _send_until_done
    return self.connection.send(data)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1630, in send
    self._raise_ssl_error(self._ssl, result)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1538, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
OSError: (32, 'EPIPE')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/utils.py", line 82, in request
    response = requests.request(method, url, **kwargs)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./webGLheatmap.py", line 118, in <module>
    py.iplot(fig, filename='basic heatmapgl')
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 160, in iplot
    url = plot(figure_or_data, **plot_options)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 257, in plot
    response = v1.clientresp(data, **plot_options)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/clientresp.py", line 35, in clientresp
    response = request('post', url, data=payload)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/utils.py", line 89, in request
    raise exceptions.PlotlyRequestError(message, status_code, content)
plotly.exceptions.PlotlyRequestError: No message
```

here is the python code to create the heatmap. 
 
```
trace = dict(type='heatmap',x=familyOrder,y=genomeOrder, z=z_data, showlegend = False, colorscale = [[0, 'rgb(255,255,255)'], [1, 'rgb(0,0,0)']] )
data = [trace]

layout = dict(
    width=1500,
    height=700,
    xaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    ),
    yaxis=dict(
        autorange=True,
        showgrid=False,
        zeroline=False,
        showline=False,
        ticks='',
        showticklabels=False
    )
)

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(
        id='genomic-map',
        figure={
            'data':[trace],
            'layout':layout,
        }
    ),
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by jonmmease** [comment]
Thanks for the report @raphael-upmc.  Could you move this to the Dash project at https://github.com/plotly/dash so that the Dash team can take a look? Thanks!

**Comment by raphael-upmc** [comment]
> Hi there,
> 
> I'm using Plot.ly and Dash, I would like to say that both are a super cool tools! I use them in order to create interactive heatmaps and it used to work very well with a binary matrice of ~2700 rows and ~900 columns. However, I get errors with a larger matrix (1000 row and 22000 columns). Looks like the matrix is too large. Is there a way to deal with such a large matrix ?
> 
> Best,
> 
> Raphael
> 
> below is the errors raised:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 304, in _send_until_done
>     return self.connection.send(data)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1630, in send
>     self._raise_ssl_error(self._ssl, result)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1538, in _raise_ssl_error
>     raise SysCallError(errno, errorcode.get(errno))
> OpenSSL.SSL.SysCallError: (32, 'EPIPE')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1065, in _send_output
>     self.send(chunk)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 986, in send
>     self.sock.sendall(data)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
>     sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
>     raise SocketError(str(e))
> OSError: (32, 'EPIPE')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 1065, in _send_output
>     self.send(chunk)
>   File "/Users/raphael/anaconda3/lib/python3.6/http/client.py", line 986, in send
>     self.sock.sendall(data)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 316, in sendall
>     sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
>     raise SocketError(str(e))
> urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/utils.py", line 82, in request
>     response = requests.request(method, url, **kwargs)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./webGLheatmap.py", line 118, in <module>
>     py.iplot(fig, filename='basic heatmapgl')
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 160, in iplot
>     url = plot(figure_or_data, **plot_options)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/plotly/plotly.py", line 257, in plot
>     response = v1.clientresp(data, **plot_options)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/clientresp.py", line 35, in clientresp
>     response = request('post', url, data=payload)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
>     return Retrying(*dargs, **dkw).call(f, *args, **kw)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 206, in call
>     return attempt.get(self._wrap_exception)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 247, in get
>     six.reraise(self.value[0], self.value[1], self.value[2])
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/retrying.py", line 200, in call
>     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
>   File "/Users/raphael/anaconda3/lib/python3.6/site-packages/plotly/api/v1/utils.py", line 89, in request
>     raise exceptions.PlotlyRequestError(message, status_code, content)
> plotly.exceptions.PlotlyRequestError: No message
> ```
> here is the python code to create the heatmap.
> 
> ```
> trace = dict(type='heatmap',x=familyOrder,y=genomeOrder, z=z_data, showlegend = False, colorscale = [[0, 'rgb(255,255,255)'], [1, 'rgb(0,0,0)']] )
> data = [trace]
> 
> layout = dict(
>     width=1500,
>     height=700,
>     xaxis=dict(
>         autorange=True,
>         showgrid=False,
>         zeroline=False,
>         showline=False,
>         ticks='',
>         showticklabels=False
>     ),
>     yaxis=dict(
>         autorange=True,
>         showgrid=False,
>         zeroline=False,
>         showline=False,
>         ticks='',
>         showticklabels=False
>     )
> )
> 
> app = dash.Dash(__name__)
> 
> app.layout = html.Div([
>     dcc.Graph(
>         id='genomic-map',
>         figure={
>             'data':[trace],
>             'layout':layout,
>         }
>     ),
> ])
> 
> if __name__ == '__main__':
>     app.run_server(debug=True)
> ```
