### ISSUE TITLE
Custom axis font in subplot

### ISSUE THREAD

**Issue by Eetion** [plotly/plotly.py#1562]
There seems to be a bug in writing custom axis fonts for subplots:
```
>>> fig = tools.make_subplots(rows=1,cols=1)
>>> fig['layout']['yaxis1'].update(showline=True)
layout.YAxis({
    'anchor': 'x', 'domain': [0.0, 1.0], 'showline': True
})
>> fig['layout']['yaxis1'].update(titlefont=dict(size=10))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/anaconda3/envs/psyneulink_py36/lib/python3.6/site-packages/plotly/basedatatypes.py", line 3021, in update
    BaseFigure._perform_update(self, kwargs)
  File "/anaconda3/envs/psyneulink_py36/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2249, in _perform_update
    validator = plotly_obj._get_prop_validator(key)
  File "/anaconda3/envs/psyneulink_py36/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2622, in _get_prop_validator
    return self._validators[prop]
KeyError: 'titlefont'

```

**Comment by Eetion** [comment]
Found a workaround:

```
>>> fig['layout']['yaxis1']['title'].update(font=dict(size=10))
layout.yaxis.Title({
    'font': {'size': 10}
})
```

This should probably be documented somewhere!

**Comment by jonmmease** [comment]
Hi @Eetion, thanks for the report.  What version of plotly.py do you have installed?  I'm not seeing the error on master.  If you're not on 3.9, could you try updating and see if you still see the error?  Thanks!

**Comment by Eetion** [comment]
Hi @jonmmease, thank you!  The upgrade fixed it.
