### ISSUE TITLE
[BUG] "_docstring_gen"  on  PYTHONOTIMIZE=2 breaks plotly

### ISSUE THREAD

**Issue by salembream** [plotly/plotly.py#2101]
### Plotly Version:
latest == 4.4.1

### The Problem:
When I run dash [ which internally uses plotly ], if I set the environment to use python optimization = 2 aka [PYTHONOTIMIZE=2], this breaks my program.
- it tries to read **\_\_doc\_\_** property from plotly.io functions which are removed/optimized-out.

### Workaround:
My workaround is just to remove/comment-out  **\_docstring\_gen**  from imports in **plotly/\_\_init\_\_.py** file.
everything worked fine for me.

### Comment:
I know the authors may not see this as a bug, but I still believe it is,  why? I know that PYTHONOTIMIZE is not a real optimization and doesn't not increase the performance a lot, but when using many big libraries in one project then at step of freezing/packaging the project it will be very helpful to reduce the size of the output package [ this will speed up sharing the files,  also more important it speeds up loading the program before running! ] .
hence, this is really useful because python freezing is already produce large files, the full packages all stored, not just the required parts as in compilation.

Hopefully I can use this in next versions without patching my installed library files. 

### Proposed Solution
- maybe by adding some kind of environment variable for plotly.
- or a more lazy solution by splitting the  import of  **\_docstring\_gen**  from the others and wrapping it around **try: import except: ** , it's pythonic :smile: 

Thanks.

BTW, Plotly is just GREAT <3.

**Comment by emmanuelle** [comment]
Hi @salembream thanks for the report and for your kind words. Could you please paste here the full error? When I try to run a dummy Dash app importing plotly with `PYTHONOPTIMIZE=2`, the error message is due to `ipywidgets` as shown below
```
emma@plotty:~/sandbox$ python3 dash_plot.py 
Traceback (most recent call last):
  File "dash_plot.py", line 4, in <module>
    import dash
  File "/home/emma/.local/lib/python3.7/site-packages/dash/__init__.py", line 1, in <module>
    from .dash import Dash, no_update  # noqa: F401
  File "/home/emma/.local/lib/python3.7/site-packages/dash/dash.py", line 23, in <module>
    import plotly
  File "/home/emma/code/plotly.py/packages/python/plotly/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/home/emma/code/plotly.py/packages/python/plotly/plotly/graph_objs/__init__.py", line 100161, in <module>
    import ipywidgets
  File "/home/emma/.local/lib/python3.7/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/home/emma/.local/lib/python3.7/site-packages/ipywidgets/widgets/__init__.py", line 13, in <module>
    from .widget_box import Box, HBox, VBox, GridBox
  File "/home/emma/.local/lib/python3.7/site-packages/ipywidgets/widgets/widget_box.py", line 33, in <module>
    class Box(DOMWidget, CoreWidget):
  File "/home/emma/.local/lib/python3.7/site-packages/ipywidgets/widgets/docutils.py", line 11, in decorator
    cls.__doc__ = cls.__doc__.format(**stripped_snippets)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by salembream** [comment]
Hi @emmanuelle , thanks for your reply.   

```
#    ./test.py  ::  testing file 
import plotly
print('hello Plotly')
```

##### 
Run using:  
`PYTHONOPTIMIZE=2 python3 ./test.py`

Result:
```
Traceback (most recent call last):
  File "./bbbb.py", line 15, in <module>
    import plotly
  File "/usr/local/lib/python3.7/dist-packages/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/usr/local/lib/python3.7/dist-packages/plotly/_docstring_gen.py", line 20, in <module>
    copy_doc_without_fig(pio.show, BaseFigure.show)
  File "/usr/local/lib/python3.7/dist-packages/plotly/_docstring_gen.py", line 13, in copy_doc_without_fig
    docstr = _re.sub(r" {4}fig:(?:.*?\n)*? {4}(\w+)", r"    \1", from_fn.__doc__)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```

I didn't  have **ipysidgets** previously installed, 
mayby it's an optional dependency for **plotly**.

To test I installed ipywidgets `pip3 install ipywidgets`, 
And then I had same result as you had!. 

so apparently **ipywidgets** also has a problem with PYTHONOPTIMIZE=2 .
and since it's  imported before **\_docstring\_gen** , then you it will break the running before reaching importing  **\_docstring\_gen**. 

I don't know why this, 
but I do use many libraries _"including big ones"_ and I saw this just in plotly and now ipywidgets :/ .
