### ISSUE TITLE
BigQuery Tutorial is broken: https://plotly.com/python/google-big-query/

### ISSUE THREAD

**Issue by jvschoen** [plotly/plotly.py#2370]
Started the tutorial and plotly fails to load.
I pip installed Dash to get plotly.

```
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/jvschoen/src_jellyfish/dashboards/venv/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/Users/jvschoen/src_jellyfish/dashboards/venv/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```
This is the pip freeze:
```
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.1
dash==1.10.0
dash-core-components==1.9.0
dash-html-components==1.0.3
dash-renderer==1.3.0
dash-table==4.6.2
Flask==1.1.2
Flask-Compress==1.4.0
future==0.18.2
google-api-core==1.16.0
google-api-python-client==1.8.0
google-auth==1.13.1
google-auth-httplib2==0.0.3
googleapis-common-protos==1.51.0
httplib2==0.17.1
idna==2.9
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
numpy==1.18.2
pandas==1.0.3
plotly==4.6.0
protobuf==3.11.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-dateutil==2.8.1
python-gflags==3.1.2
pytz==2019.3
requests==2.23.0
retrying==1.3.3
rsa==4.0
six==1.14.0
uritemplate==3.0.1
urllib3==1.25.8
Werkzeug==1.0.1
```

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! This is an old and out of date documentation page which I should remove from our site :)
