### ISSUE TITLE
Jupyterlab install is failing

### ISSUE THREAD

**Issue by RohitR1** [plotly/plotly.py#2458]
I tried: `jupyter labextension install jupyterlab-plotly@4.7.1`

Error:
```
$ cat /tmp/jupyterlab-debug-blnt0q9g.log
Node v13.13.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack jupyterlab-plotly@4.7.1
npm notice
npm notice 📦  jupyterlab-plotly@4.7.1
npm notice === Tarball Contents ===
npm notice 1.0kB package.json
npm notice 156B  README.md
npm notice 6.3kB dist/javascript-renderer-extension.js
npm notice 545B  style/index.css
npm notice 1.0kB style/plotly.svg
npm notice === Tarball Details ===
npm notice name:          jupyterlab-plotly
npm notice version:       4.7.1
npm notice filename:      jupyterlab-plotly-4.7.1.tgz
npm notice package size:  3.1 kB
npm notice unpacked size: 9.1 kB
npm notice shasum:        655c1169137a5c8efb525778146cb679e9645bfe
npm notice integrity:     sha512-/h/95B9m3MXIl[...]RvIS0BlC+iDnw==
npm notice total files:   5
npm notice
jupyterlab-plotly-4.7.1.tgz

Node v13.13.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyterlab-plotly > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning jupyterlab-plotly > plotly.js > point-cluster > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @jupyterlab/git@0.20.0" has unmet peer dependency "codemirror@^5.0.0".
warning "@jupyterlab/git > nbdime@6.0.0" has unmet peer dependency "codemirror@^5.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme@^3.6.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme-adapter-utils@^1.13.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "react-test-renderer@^16.4.1".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react-dom@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm > react-test-renderer@16.13.1" has incorrect peer dependency "react@^16.13.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 36.75s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @jupyterlab/git@0.20.0" has unmet peer dependency "codemirror@^5.0.0".
warning "@jupyterlab/git > nbdime@6.0.0" has unmet peer dependency "codemirror@^5.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme@^3.6.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "enzyme-adapter-utils@^1.13.0".
warning "keplergl-jupyter > kepler.gl > react-palm@3.2.2" has unmet peer dependency "react-test-renderer@^16.4.1".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-tooltip@3.11.6" has incorrect peer dependency "react-dom@>=^16.0.0".
warning "keplergl-jupyter > kepler.gl > react-palm > react-test-renderer@16.13.1" has incorrect peer dependency "react@^16.13.1".
[5/5] Building fresh packages...
Done in 16.89s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
Hash: 18e0bdb51ba9e5afbe22c16c1e191e6ee74c5543a3a9631c63c598ea4d2f
Version: webpack 4.43.0
Child
    Hash: 18e0bdb51ba9e5afbe22
    Time: 220822ms
    Built at: 05/11/2020 12:59:52 PM
     33 assets
    Entrypoint main = vendors~main.31ea615678368029653c.js vendors~main.31ea615678368029653c.js.map main.ce58681a6db5dc0e8c0e.js main.ce58681a6db5dc0e8c0e.js.map
    [3] multi whatwg-fetch ./build/index.out.js 40 bytes {0} [built]
    [/KN4] ./node_modules/@jupyterlab/filebrowser-extension/lib/index.js + 6 modules 134 KiB {2} [optional] [built]
        |    7 modules
    [31N0] ./node_modules/@jupyterlab/csvviewer-extension/lib/index.js + 5 modules 66.7 KiB {2} [optional] [built]
        |    6 modules
    [5pV8] ./node_modules/@jupyterlab/mathjax2-extension/lib/index.js + 1 modules 4.15 KiB {2} [optional] [built]
        |    2 modules
    [93mg] ./node_modules/@jupyterlab/celltags-extension/lib/index.js + 3 modules 15.7 KiB {2} [optional] [built]
        |    4 modules
    [9fgM] ./build/imports.css 463 bytes {0} [built]
    [ANye] ./build/index.out.js 33.1 KiB {0} [built]
    [J1oh] ./node_modules/jupyterlab_tensorboard/lib/index.js + 4 modules 32.5 KiB {2} [optional] [built]
        |    5 modules
    [KKbn] ./node_modules/@jupyter-widgets/jupyterlab-manager/lib/index.js + 7 modules 34.2 KiB {2} [optional] [built]
        |    8 modules
    [NHPb] ./node_modules/@jupyterlab/console-extension/lib/index.js + 1 modules 22.2 KiB {2} [optional] [built]
        |    2 modules
    [QP8U] ./node_modules/@jupyterlab/fileeditor-extension/lib/index.js + 1 modules 34.7 KiB {2} [optional] [built]
        |    2 modules
    [RMrj] ./node_modules/@jupyterlab/inspector-extension/lib/index.js + 1 modules 8.68 KiB {2} [optional] [built]
        |    2 modules
    [U33M] ./node_modules/@jupyterlab/logconsole-extension/lib/index.js + 5 modules 45.7 KiB {2} [optional] [built]
        |    6 modules
    [VYmV] ./node_modules/@jupyterlab/completer-extension/lib/index.js + 7 modules 62.9 KiB {2} [optional] [built]
        |    8 modules
    [ZPDT] ./node_modules/@jupyterlab/extensionmanager-extension/lib/index.js + 7 modules 57.3 KiB {2} [optional] [built]
        |    8 modules
        + 3561 hidden modules

    WARNING in ./node_modules/moment/locale/en-SG.js
    There are multiple modules with names that only differ in casing.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Use equal casing. Compare these module identifiers:
    * /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale/en-SG.js
        Used by 2 module(s), i. e.
        /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale sync /^\.\/.*$/
    * /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale/en-sg.js
        Used by 2 module(s), i. e.
        /opt/conda/share/jupyter/lab/staging/node_modules/moment/locale sync /^\.\/.*$/
     @ ./node_modules/moment/locale/en-SG.js
     @ ./node_modules/moment/locale sync ^\.\/.*$
     @ ./node_modules/moment/moment.js
     @ ./node_modules/kepler.gl/dist/utils/data-utils.js
     @ ./node_modules/kepler.gl/dist/reducers/combined-updaters.js
     @ ./node_modules/kepler.gl/dist/reducers/index.js
     @ ./node_modules/kepler.gl/reducers.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl/store.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl/kepler.gl.js
     @ ./node_modules/keplergl-jupyter/babel/keplergl-plugin.js
     @ ./node_modules/keplergl-jupyter/babel/index.js
     @ ./node_modules/keplergl-jupyter/babel/labplugin.js
     @ ./build/index.out.js
     @ multi whatwg-fetch ./build/index.out.js

    ERROR in vendors~main.31ea615678368029653c.js from Terser
    Error: Call retries were exceeded
        at ChildProcessWorker.initialize (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:191:21)
        at ChildProcessWorker._onExit (/opt/conda/share/jupyter/lab/staging/node_modules/jest-worker/build/workers/ChildProcessWorker.js:268:12)
        at ChildProcess.emit (events.js:315:20)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 703 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.27 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
            + 1 hidden module
Child
    Hash: c16c1e191e6ee74c5543
    Time: 6045ms
    Built at: 05/11/2020 12:56:18 PM
        Asset       Size  Chunks             Chunk Names
    index.css   15.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-dark-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
Child
    Hash: a3a9631c63c598ea4d2f
    Time: 6036ms
    Built at: 05/11/2020 12:56:18 PM
        Asset       Size  Chunks             Chunk Names
    index.css   14.7 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       3 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-light-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           3 modules
child_process.js:632
    throw err;
    ^

Error: Command failed: /opt/conda/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 1877,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by sackh** [comment]
I am also facing the same issue.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
