### ISSUE TITLE
Unable to find orca in a jupyter kernel

### ISSUE THREAD

**Issue by sprague252** [plotly/plotly.py#2628]
I am trying to generate a static image from plotly using Jupyter Lab. I am using a kernel that is not my base conda environment, and plotly cannot find Orca. The package plotly-orca is installed in my kernel environment but not my base environment. If I run Jupyter Lab from within the environment of my kernel (plotly-orca installed and not the base environment) there is no error. I think that the path to the Orca code that plotly requires to generate a static image is not modified by a Jupyter kernel that is different from the environment running the Jupyter server. Here is a minimal example.

First I run Jupyter Lab in my base conda environment. (The package plotly-orca is not installed in my base environment.) I open a new notebook with a kernel from an environment in which plotly and plotly-orca are both installed and execute the following commands:
```
import numpy as np
import plotly.graph_objects as go
x = np.arange(100) * 2 * np.pi/100
y = np.sin(x)
fig = go.Figure(go.Scatter(x=x, y=y))
fig.write_image("filenams.pdf")
```
The error message is below.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-7500fd6a13a1> in <module>
----> 1 fig.write_image("filenams.pdf")

/opt/anaconda3/envs/svphysics/lib/python3.6/site-packages/plotly/basedatatypes.py in write_image(self, *args, **kwargs)
   3238         import plotly.io as pio
   3239 
-> 3240         return pio.write_image(self, *args, **kwargs)
   3241 
   3242     # Static helpers

/opt/anaconda3/envs/svphysics/lib/python3.6/site-packages/plotly/io/_orca.py in write_image(fig, file, format, scale, width, height, validate)
   1768     # Do this first so we don't create a file if image conversion fails
   1769     img_data = to_image(
-> 1770         fig, format=format, scale=scale, width=width, height=height, validate=validate
   1771     )
   1772 

/opt/anaconda3/envs/svphysics/lib/python3.6/site-packages/plotly/io/_orca.py in to_image(fig, format, width, height, scale, validate)
   1533     # Make sure orca sever is running
   1534     # -------------------------------
-> 1535     ensure_server()
   1536 
   1537     # Handle defaults

/opt/anaconda3/envs/svphysics/lib/python3.6/site-packages/plotly/io/_orca.py in ensure_server()
   1388         # Validate orca executable only if server_url is not provided
   1389         if status.state == "unvalidated":
-> 1390             validate_executable()
   1391         # Acquire lock to make sure that we keep the properties of orca_state
   1392         # consistent across threads

/opt/anaconda3/envs/svphysics/lib/python3.6/site-packages/plotly/io/_orca.py in validate_executable()
   1182 for more info on Xvfb
   1183 """
-> 1184         raise ValueError(err_msg)
   1185 
   1186     if not help_result:

ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/opt/anaconda3/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

Here is the error that was returned by the command
    $ /opt/anaconda3/bin/orca --help

[Return code: 1]
internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module 'electron'
Require stack:
- /opt/anaconda3/lib/node_modules/orca/bin/orca.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/anaconda3/lib/node_modules/orca/bin/orca.js:5:84)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/anaconda3/lib/node_modules/orca/bin/orca.js' ]
}
```
Note that in my installation `/opt/anaconda3` is my base conda environment, and `/opt/anaconda3/envs/svphysics` is the environment of my kernel (in which plotly-orca is installed).

**Comment by sprague252** [comment]
Here are the versions of the plotly packages installed in my non-base environment:
```
plotly                    4.8.2              pyh9f0ad1d_0    conda-forge
plotly-orca               1.3.1                         1    plotly
```
Here are the jupyter packages installed in my base environment (where I ran Jupyter Lab).
```
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.5                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.1.5                      py_0    conda-forge
jupyterlab_server         1.1.5                      py_0    conda-forge
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
