### ISSUE TITLE
Hey all, I have been trying to get Plotly to work with Pyinstaller uncessfully but in my attempts I seem to have broken it.............

### ISSUE THREAD

**Issue by StrangeCalibur** [plotly/plotly.py#2853]
Hey all!

I have been trying to get Plotly to work with Pyinstaller uncessfully but in my attempts I seem to have broken it.............

Now when I run a script that always worked before I get the following: 

```
Traceback (most recent call last):
  File "C:/Users/a1069763/PycharmProjects/JRM_python_toolkit/DAF_RF_Sanity.py", line 2388, in <module>
    fig1 = go.Figure(data=[go.Table(header=dict(values=['Wheel Position', 'ID', 'AvgSNR', 'AvgRSSI', 'Frame %']),
  File "C:\Users\a1069763\PycharmProjects\JRM_python_toolkit\venv\lib\site-packages\plotly\graph_objs\__init__.py", line 9921, in __init__
    from plotly.validators import table as v_table
ImportError: cannot import name 'table' from 'plotly.validators' (C:\Users\a1069763\PycharmProjects\JRM_python_toolkit\venv\lib\site-packages\plotly\validators\__init__.py)
```

I have tried searching for this issue but have been unable to find anything. I also saw a similar error when trying to open the exe created by pyinstaller.
![image](https://user-images.githubusercontent.com/15046126/96765908-3816a480-13d2-11eb-865a-d01658a46411.png)

Not sure if the two issues are related or not.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
