### ISSUE TITLE
Plotly Installation - RuntimeError: JupyterLab failed to build

### ISSUE THREAD

**Issue by AntttMan** [plotly/plotly.py#3093]
I'm trying to install Plotly extensions to my Jupyter Lab environment, following the instructions [here](https://plotly.com/python/getting-started/).

However, when I run ``` jupyter labextension install jupyterlab-plotly@4.14.3```,  I get

```
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-l7o8nq7l.log
```

I include the log file below. Sorry for the length, but I have no idea how to proceed to fix this, after trying to understand the log file.

```
Node v10.19.0

Yarn configuration loaded.
> /usr/bin/npm pack jupyterlab-plotly@4.14.3
npm notice 
npm notice ðŸ“¦  jupyterlab-plotly@4.14.3
npm notice === Tarball Contents === 
npm notice 545B  style/index.css                      
npm notice 6.3kB dist/javascript-renderer-extension.js
npm notice 1.0kB package.json                         
npm notice 156B  README.md                            
npm notice 1.0kB style/plotly.svg                     
npm notice === Tarball Details === 
npm notice name:          jupyterlab-plotly                       
npm notice version:       4.14.3                                  
npm notice filename:      jupyterlab-plotly-4.14.3.tgz            
npm notice package size:  3.1 kB                                  
npm notice unpacked size: 9.1 kB                                  
npm notice shasum:        bb424a50226c2ce1b816f061a8123f0f42418fc0
npm notice integrity:     sha512-6ZdmIQ5fDiBTY[...]nASwRNCf1U1Cg==
npm notice total files:   5                                       
npm notice 
jupyterlab-plotly-4.14.3.tgz

Node v10.19.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /root/miniconda3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.27s.

> node /root/miniconda3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /root/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> node /root/miniconda3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
Done in 6.94s.

> node /root/miniconda3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:650
    throw err;
    ^

Error: Command failed: /root/miniconda3/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at Object.<anonymous> (/root/miniconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/root/miniconda3/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/root/miniconda3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "/root/miniconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/root/miniconda3/lib/python3.8/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

I'm running Python 3.8.5 and JupyterLab 6.2.0.

**Comment by rmerz** [comment]
I have the same issue, I've been able to solve it via
jupyter labextension install jupyterlab-plotly --no-build && jupyter lab build --dev-build

But trying to build the production version (without the --dev-build flag) fails as well.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
