### ISSUE TITLE
Holidays on week days

### ISSUE THREAD

**Issue by rickpm** [plotly/plotly.py#3134]
Hi Folks,

I am having issues when I have holidays on week days.
if I exclude weekends and have a holiday on Friday there is a bug

    rangebreaks=[
        # NOTE: Below values are bound (not single values), ie. hide x to y
        dict(bounds=['sat', 'mon']),  # hide weekends, eg. hide sat to before mon
        dict(bounds=[18, 9], pattern='hour'),  # hide hours outside of 9.30am-4pm
        dict(values=["2021-04-02", "2021-12-25"]),  # hide holidays (Christmas and New Year's, etc)
    ]

(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read property 'val' of undefined

    at u (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2417931)

    at doAutoRange (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2420435)

    at Object.r.doAutoRangeAndConstraints (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2400288)

    at S (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2374022)

    at Object.c.syncOrAsync (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2287218)

    at http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2375512

    at Object.c.syncOrAsync (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2287218)

    at Object.r.plot (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2376077)

    at Object.r.newPlot (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2370936)

    at Object.r.react (http://127.0.0.1:8050/_dash-component-suites/dash_core_components/async-plotlyjs.v1_15_0m1611086576.js:2:2380532)

**Comment by A-Wpro** [comment]
I got the same problem with a similar code, I can confirm @gtarabat analysis, if you use bounds with rangebreak a big part of the graph, eventually all the graph is missing. It seems to be a bug that already occurred in 2020 and still exists today.

**Comment by A-Wpro** [comment]
If someone is still looking for a way to make a rangebreak **without** using bounds you can use this : 

` 
 rangebreaks=[dict(pattern="hour",dvalue = 6*24*60*60*1000-7*60*60*1000, values=["2020-01-01 17:00:00"])]
`


values are the start of every break you want. Here we want only 1 break starting at "2020-01-01 17:00:00"
dvalue is the duration of each break. Here we have a break of 6 days - 7 hours. 
(6d * 24h * 60m * 60sec * 1000ms - 7h * 60m * 60sec * 1000ms)

Of course, there is still a problem to fix.
