### ISSUE TITLE
QuickFix: make_subplots() error when trying to create a 3x3 grid

### ISSUE THREAD

**Issue by Dseal95** [plotly/plotly.py#3147]
Hi, 

I have a relatively easy question but I cannot seem to get past an error when trying to create subplots. 

I am trying to create a 3x3 grid using: 

```
    fig = make_subplots(rows=3, cols=3,
                        column_widths=[0.5, 0.25, 0.25],
                        specs=[[{'rowspan': 3, 'colspan': 1}, None, None], 
                               [{}, {}, {}], 
                               [{'rowspan': 3, 'colspan': 1}, None, None]]
                        )
```

but the code keeps giving me the following error (full trace):

`Traceback (most recent call last):
  File "/Users/danielseal/aa_repos/angloamerican.analytics.processhealth.core/.venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-b90efa106d9a>", line 4, in <module>
    [{'rowspan': 3, 'colspan': 1}, None, None]]
  File "/Users/danielseal/aa_repos/angloamerican.analytics.processhealth.core/.venv/lib/python3.7/site-packages/plotly/subplots.py", line 689, in make_subplots
    "Some 'rowspan' value is too large for " "this subplot grid."
Exception: Some 'rowspan' value is too large for this subplot grid.`

I am sure that my list is a 2D list of dimensions (3x3) !

**Comment by Dseal95** [comment]
`    fig = make_subplots(rows=3, cols=3,
                        column_widths=[0.5, 0.25, 0.25],
                        specs=[[{'rowspan': 3, 'colspan': 1}, None, {'rowspan': 3, 'colspan': 1}], 
                               [None, {}, None], 
                               [None, {}, None]]
                        )`

Fix for issue
