### ISSUE TITLE
Jupyter labextension Fail to build, error package.json cannot be found

### ISSUE THREAD

**Issue by cocojim** [plotly/plotly.py#3207]
hi, 

I am having issue trying to 'jupyter labextension build'.  Any guidance would be greatly appreciated please.

here is the **jupyter labextension list**
JupyterLab v3.0.14
C:\Users\xxxx\.conda\envs\jz\share\jupyter\labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled ok (python, voila)

Other labextensions (built into JupyterLab)
   app dir: C:\Users\xxxx\.conda\envs\jz\share\jupyter\lab
        jupyterlab-plotly v4.14.3 enabled ok
        plotlywidget v4.14.3 enabled ok

as u can see, evythign pretty much the most up to date and in 'sync'.

**the log** looks this:

Building extension in C:\Users\xxxxx
Traceback (most recent call last):

  File "C:\Users\xxxxx\.conda\envs\jz\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\xxxxx\.conda\envs\jz\lib\site-packages\jupyterlab\labextensions.py", line 128, in start
    ans = self.run_task()

  File "C:\Users\xxxxx\.conda\envs\jz\lib\site-packages\jupyterlab\labextensions.py", line 227, in run_task
    build_labextension(self.extra_args[0], logger=self.log, development=self.development, static_url=self.static_url or None, source_map = self.source_map,

  File "C:\Users\xxxxx\.conda\envs\jz\lib\site-packages\jupyterlab\federated_labextensions.py", line 168, in build_labextension
    builder = _ensure_builder(ext_path, core_path)

  File "C:\Users\xxxxx\.conda\envs\jz\lib\site-packages\jupyterlab\federated_labextensions.py", line 226, in _ensure_builder
    with open(osp.join(ext_path, 'package.json')) as fid:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\package.json'

Exiting application: lab

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
