### ISSUE TITLE
ValueError when adding custom title to plotly express bar plot

### ISSUE THREAD

**Issue by mcoirad-gmmb** [plotly/plotly.py#3402]
Forgive me if I am using things incorrectly

Running the following:

```
import plotly.express as px
import plotly.graph_objects as go  

data_canada = px.data.gapminder().query("country == 'Canada'")
fig = px.bar(data_canada, x='year', y='pop', title = go.layout.Title(
                        text=str("Test title")
                    ))
```

Produces:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 365, in bar
    return make_figure(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/express/_core.py", line 2191, in make_figure
    fig.update_layout(layout_patch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 1403, in update_layout
    self.layout.update(dict1, overwrite=overwrite, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 5081, in update
    BaseFigure._perform_update(self, dict1, overwrite=overwrite)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 3921, in _perform_update
    plotly_obj[key] = val
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 5810, in __setitem__
    super(BaseLayoutHierarchyType, self).__setitem__(prop, value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 4859, in __setitem__
    res[prop[-1]] = value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 4819, in __setitem__
    self._set_prop(prop, value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 5163, in _set_prop
    raise err
  File "/home/ubuntu/.local/lib/python3.8/site-packages/plotly/basedatatypes.py", line 5158, in _set_prop
    val = validator.validate_coerce(val)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/_plotly_utils/basevalidators.py", line 1103, in validate_coerce
    self.raise_invalid_val(v)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/_plotly_utils/basevalidators.py", line 289, in raise_invalid_val
    raise ValueError(
ValueError: 
    Invalid value of type 'plotly.graph_objs.layout._title.Title' received for the 'text' property of layout.title
        Received value: layout.Title({
    'text': 'Test title'
})

    The 'text' property is a string and must be specified as:
      - A string
      - A number that will be converted to a string

**Comment by nicolaskruchten** [comment]
Yes, the `title` argument to Plotly Express functions is written to `layout.title.text` so you cannot pass a `go.layout.Title` object there :)

**Comment by mcoirad-gmmb** [comment]
Sorry and thank you!

**Comment by nicolaskruchten** [comment]
No need to apologize, and you're welcome!
