### ISSUE TITLE
Unable to contribute due to missing files error

### ISSUE THREAD

**Issue by sudeepag** [plotly/plotly.py#3736]
Hi, I am trying to follow the steps outlined [here](https://github.com/plotly/plotly.py/blob/master/contributing.md#editable-install-of-plotly-packages), but run into the following error when running

```
$ pip install -e packages/python/plotly/
```

Please let me know how I can resolve this so I can install a local copy of plotly in my virtual environment. Thanks!

```
(plotly-dev) ➜  plotly.py git:(master) ✗ pip install -e packages/python/plotly/
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Obtaining file:///Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sudeep/opt/anaconda3/envs/plotly-dev/bin/python /Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/tmpfs1a6n90
       cwd: /Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly
  Complete output (92 lines):
  /private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  /private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/dist.py:318: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running egg_info
  running jsdeps
  8.10.0
  8.10.0
  Installing build dependencies with npm.  This may take a while...

  up to date, audited 744 packages in 1s

  76 packages are looking for funding
    run `npm fund` for details

  found 0 vulnerabilities

  > jupyterlab-plotly@5.8.0 build:prod
  > npm run build:lib && npm run build:nbextension && npm run build:labextension


  > jupyterlab-plotly@5.8.0 build:lib
  > tsc


  > jupyterlab-plotly@5.8.0 build:nbextension
  > webpack --mode=production

  /Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/loader-runner/lib/LoaderRunner.js:146
  		if(isError) throw e;
  		            ^

  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:135:10)
      at BulkUpdateDecorator.hashFactory (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/util/createHash.js:144:18)
      at BulkUpdateDecorator.update (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/util/createHash.js:46:50)
      at RawSource.updateHash (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
      at NormalModule._initBuildHash (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/NormalModule.js:838:17)
      at handleParseResult (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/NormalModule.js:903:10)
      at /Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/NormalModule.js:994:4
      at processResult (/Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/NormalModule.js:717:11)
      at /Users/sudeep/Documents/plotly-dev/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/NormalModule.js:777:5 {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }

  Node.js v17.9.0
  rebuilding js and css failed
  missing files: ['/Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly/jupyterlab_plotly/nbextension/index.js', '/Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly/jupyterlab_plotly/labextension/package.json']
  Traceback (most recent call last):
    File "/Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 495, in <module>
      setup(
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 104, in run
      raise e
    File "setup.py", line 97, in run
      self.distribution.run_command("jsdeps")
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/private/var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/pip-build-env-qcsr__nz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 190, in run
      check_call(
    File "/Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['npm', 'run', 'build:prod']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding file:///Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly. Command errored out with exit status 1: /Users/sudeep/opt/anaconda3/envs/plotly-dev/bin/python /Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/tmpfs1a6n90 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/sudeep/opt/anaconda3/envs/plotly-dev/bin/python /Users/sudeep/opt/anaconda3/envs/plotly-dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/qb/r7l597td2jx99_w3f5w8mzxc0000gn/T/tmpfs1a6n90 Check the logs for full command output.
```

**Comment by sudeepag** [comment]
Perhaps this is most relevant?

```
missing files: ['/Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly/jupyterlab_plotly/nbextension/index.js', '/Users/sudeep/Documents/plotly-dev/plotly.py/packages/python/plotly/jupyterlab_plotly/labextension/package.json']
```

**Comment by sudeepag** [comment]
Same error when running 

```
python setup.py updateplotlyjs
```

**Comment by nicolaskruchten** [comment]
Hmm, do you see the same error when you `cd packages/python/plotly` and then `pip install -e .` ?

**Comment by nicolaskruchten** [comment]
It seems like the JS build is failing due to some SSL error, which I'm not sure how to diagnose... `ERR_OSSL_EVP_UNSUPPORTED` is the key thing here. This causes the JS build to fail and then downstream Python build steps fail because the expected JS build outputs aren't present.

**Comment by nicolaskruchten** [comment]
I'll close this as a duplicate of https://github.com/plotly/plotly.py/issues/3669 for now.

**Comment by sudeepag** [comment]
> Hmm, do you see the same error when you `cd packages/python/plotly` and then `pip install -e .` ?

Same thing, unfortunately.
