### ISSUE TITLE
Problem following How to Contribute (Windows + Conda) - possibly add Nodejs to optional requirements

### ISSUE THREAD

**Issue by lukefeilberg** [plotly/plotly.py#4072]
Hi all. I was running through the Windows + Conda set up instructions in the [Contributing](https://github.com/plotly/plotly.py/blob/master/contributing.md#install-requirements---windows--conda) section but once I got to the **Editable install of plotly packages** section I got the following error: 

```bash
(plotly-dev) C:\Users\lukef\plotly.py>pip install -e packages/python/plotly/
Obtaining file:///C:/Users/lukef/plotly.py/packages/python/plotly
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\config\setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\dist.py:328: DistDeprecationWarning: use_2to3 is ignored.
        warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
      running egg_info
      running jsdeps
      `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
      rebuilding js and css failed
      missing files: ['C:\\Users\\lukef\\plotly.py\\packages\\python\\plotly\\jupyterlab_plotly\\nbextension\\index.js', 'C:\\Users\\lukef\\plotly.py\\packages\\python\\plotly\\jupyterlab_plotly\\labextension\\package.json']
      Traceback (most recent call last):
        File "C:\Users\lukef\AppData\Local\Continuum\anaconda3\envs\plotly-dev\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\lukef\AppData\Local\Continuum\anaconda3\envs\plotly-dev\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\lukef\AppData\Local\Continuum\anaconda3\envs\plotly-dev\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\build_meta.py", line 447, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 495, in <module>
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 104, in run
        File "<string>", line 97, in run
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\lukef\AppData\Local\Temp\pip-build-env-mlstg81a\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 203, in run
      ValueError: Missing file: C:\Users\lukef\plotly.py\packages\python\plotly\jupyterlab_plotly\nbextension\index.js
      npm is required to build a development version of jupyterlab-plotly
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

I found a _somewhat_ similar [StackOverflow](https://stackoverflow.com/questions/61210272/jupyterlab-plotly-build-npm-extensions-failed-to-install-on-linux) question and was able to resolve it similarly by first conda installing nodejs, i.e. running...

```bash
conda install -c conda-forge nodejs
```

After that rerunning `pip install -e packages/python/plotly/` worked fine. So I'm wondering if `nodejs` should be added to the optional requirements. Thanks!

**Comment by nicolaskruchten** [comment]
Yes, I agree we should add this to the contributing guide. In fact we now have an `environment.yml` file which `conda` users can use and that should really be integrated into the docs too :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
