### ISSUE TITLE
Invalid regular expression error when running `python setup.py updateplotlyjs`

### ISSUE THREAD

**Issue by LiamConnors** [plotly/plotly.py#4166]
When running [`python setup.py updateplotlyjs`](https://github.com/plotly/plotly.py/blob/master/contributing.md#update-to-a-new-version-of-plotlyjs), it throws this error:

```

> jupyterlab-plotly@5.14.1 build:prod
> npm run build:lib && npm run build:nbextension && npm run build:labextension


> jupyterlab-plotly@5.14.1 build:lib
> tsc


> jupyterlab-plotly@5.14.1 build:nbextension
> webpack --mode=production

[webpack-cli] /Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/cli.js:68
                                /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/gu,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid property name
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (/Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at get cli (/Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/index.js:129:10)
    at Function.cli (/Users/lc/Documents/plotly.py/packages/javascript/jupyterlab-plotly/node_modules/webpack/lib/util/memoize.js:22:13)
rebuilding js and css failed (not a problem)
Command '['npm', 'run', 'build:prod']' returned non-zero exit status 2.
running updatebundle
running updateschema
running codegen
```

**Comment by LiamConnors** [comment]
@nicolaskruchten have you encountered this issue before on the build? Initially I could recreate it locally but now it just seems to be in the release build on CI.

**Comment by LiamConnors** [comment]
https://github.com/plotly/plotly.py/pull/4188
