### ISSUE TITLE
Different error fields in error response

### ISSUE THREAD

**Issue by AltxSF** [plotly/plotly.py#447]
When generating images from a batch script, I get the following error:

```
Traceback (most recent call last):
  File "utils/generate_graphs.py", line 414, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "utils/generate_graphs.py", line 123, in generate_graph
    _generate_dot_chart(correlations, obj['ObjID'] + '_postfix')
  File "utils/generate_graphs.py", line 337, in _generate_dot_chart
    _save_image(fig, filename)
  File "utils/generate_graphs.py", line 400, in _save_image
    py.image.save_as(fig, filename=absolute_path)
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 760, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 683, in get
    raise exceptions.PlotlyError(return_data['error'])
KeyError: 'error'
```

`return_data` does not have an `error` key for that specific exception. `return_data` is

```
{u'errors': [{u'path': None, u'message': u'Unknown Image Server Error', u'code': u'UNKNOWN', u'field': None}], u'detail': u'Unknown Image Server Error'}
```

I will add a pull request with defensive code to handle this, though a better solution would be to standardize the response to use `error` instead of `errors`.

**Comment by yankev** [comment]
@AltxSF Do you happen to have some shareable code that'll reproduce the issue?

**Comment by AltxSF** [comment]
Yes. It happened originally when getting my requests throttled (professional version), but you can also reproduce it if you try using the wrong credentials at `~/.plotly/credentials`. Then run:

```
import random
import plotly.plotly as py
import plotly.graph_objs as go

data = go.Bar(
    x=random.sample(range(100), 25),
    y=random.sample(range(100), 25),
    name='My Graph'
)

py.image.save_as([data], filename='out.png')
```

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    py.image.save_as([data], filename='out.png')
  File "/home/vagrant/.pyenv/versions/2.7.8/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 785, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/home/vagrant/.pyenv/versions/2.7.8/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 708, in get
    raise exceptions.PlotlyError(return_data['error'])
KeyError: 'error'
```

**Comment by jonmmease** [comment]
As of 3.2.1 the follow error message is returned

```
PlotlyRequestError: You must be authenticated to generate an image via json.
```
