### ISSUE TITLE
No version of module jupyterlab-plotly is registered (Win 11 64 bit, VS Code)

### ISSUE THREAD

**Issue by luweiming** [plotly/plotly.py#4752]
Hi There,

I'm getting this error after upgrading to the latest Plotly version 5.24.0, 

I'm using the latest VS Code version on Windows 11 64 bit. Thanks.
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Failed to load model class 'FigureModel' from module 'jupyterlab-plotly'
Error: No version of module jupyterlab-plotly is registered

Failed to load model class 'FigureModel' from module 'jupyterlab-plotly'
Error: No version of module jupyterlab-plotly is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at n._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-win32-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:80955)
    at async n._handleMessage (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/tptia/.vscode/extensions/ms-toolsai.jupyter-2024.8.0-win32-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:82830)

**Comment by gstvortiz** [comment]
same here.

**Comment by luweiming** [comment]
> same here.

temporary solution, roll back to older VS Code Version that is not 1.93.0

**Comment by gstvortiz** [comment]
Thank you very much! It worked perfectly on Ubuntu.
