### ISSUE TITLE
Sometime: raise exceptions.PlotlyError(return_data['error']) KeyError: 'error'

### ISSUE THREAD

**Issue by sohamnavadiya** [plotly/plotly.py#733]
I am using plotly lib with Django to send an email once a day with the graph. I integrated it successfully but the sometime script is showing an error. see below error trace.

It is working fine after executing same script again.

Below is the lib version:
**Django version: 1.7**
**python Plotly lib version: 1.12.9**

How can I avoid this kind of failure?

Your comments and suggestions will be appreciated

```
DEBUG 2017-04-13 02:30:17,133 connectionpool 32344 139972476417856 "POST /v2/images/ HTTP/1.1" 500 133 () null
Traceback (most recent call last):
  File "/home/ubuntu/rest_api/scripts/daily_analysis_report.py", line 132, in <module>
    main()
  File "/home/ubuntu/rest_api/scripts/daily_analysis_report.py", line 106, in main
    table_summary = pcharts.analytics_table_chart(past_days_metrics, report_params, table_title)
  File "/home/ubuntu/rest_api/scripts/plotly_charts/charts.py", line 84, in analytics_table_chart
    py.image.save_as(table, filename=file_path)
  File "/home/ubuntu/rest_api/venv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 787, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/home/ubuntu/rest_api/venv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 710, in get
    raise exceptions.PlotlyError(return_data['error'])
KeyError: 'error'
Build step 'Execute shell' marked build as failure
```

**Comment by cldougl** [comment]
Hi there,
Can you let us know if you're still experiencing this issue intermittently with an updated version of our library. We're currently on [v 2.0.7](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md)

**Comment by sohamnavadiya** [comment]
Thaks for reply.
I had run script after upgrading plotly lib to latest version **2.0.7**. It was giving below error strace.

```
DEBUG 2017-04-14 06:29:47,218 connectionpool 25306 139912598480640 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:29:48,758 connectionpool 25306 139912598480640 https://api.plot.ly:443 "GET /v2/users/current HTTP/1.1" 200 474 ('https', 'api.plot.ly', 443, 'GET', '/v2/users/current', 'HTTP/1.1', 200, 474) null
DEBUG 2017-04-14 06:29:48,825 connectionpool 25306 139912598480640 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:30:07,878 connectionpool 25306 139912598480640 https://api.plot.ly:443 "POST /v2/images HTTP/1.1" 500 133 ('https', 'api.plot.ly', 443, 'POST', '/v2/images', 'HTTP/1.1', 500, 133) null
Traceback (most recent call last):
  File "daily_analysis_report.py", line 132, in <module>
    main()
  File "daily_analysis_report.py", line 106, in main
    table_summary = pcharts.analytics_table_chart(past_days_metrics, report_params, table_title)
  File "/home/soham/cubii/cubii_backend/rest_api/scripts/plotly_charts/charts.py", line 84, in analytics_table_chart
    py.image.save_as(table, filename=file_path)
  File "/home/soham/cubii/cubii_backend/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 831, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/home/soham/cubii/cubii_backend/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 744, in get
    response = v2.images.create(payload)
  File "/home/soham/cubii/cubii_backend/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/images.py", line 18, in create
    return request('post', url, json=body)
  File "/home/soham/cubii/cubii_backend/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/utils.py", line 153, in request
    validate_response(response)
  File "/home/soham/cubii/cubii_backend/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/utils.py", line 79, in validate_response
    raise exceptions.PlotlyRequestError(message, status_code, content)
plotly.exceptions.PlotlyRequestError: Unknown Image Server Error
```
Then I run it again and It was run successfully.

**Comment by sohamnavadiya** [comment]
After performing above steps, I created a new plotly account.

I run the same script with a new credential and first time It shown below error trace.
```

DEBUG 2017-04-14 06:53:08,029 connectionpool 27334 139762766374656 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:53:09,471 connectionpool 27334 139762766374656 https://api.plot.ly:443 "GET /v2/users/current HTTP/1.1" 200 479 ('https', 'api.plot.ly', 443, 'GET', '/v2/users/current', 'HTTP/1.1', 200, 479) null
{u'sharing': u'public', u'world_readable': True, u'plotly_streaming_domain': u'stream.plot.ly', u'plotly_ssl_verification': True, u'plotly_proxy_authorization': False, u'plotly_api_domain': u'https://api.plot.ly', u'auto_open': True, u'plotly_domain': u'https://plot.ly'}
DEBUG 2017-04-14 06:53:09,591 connectionpool 27334 139762766374656 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:53:11,552 connectionpool 27334 139762766374656 https://api.plot.ly:443 "POST /v2/images HTTP/1.1" 200 None ('https', 'api.plot.ly', 443, 'POST', '/v2/images', 'HTTP/1.1', 200, None) null
This is the format of your plot grid:
[ (1,1) x1,y1 ]
[ (2,1) x2,y2 ]
[ (3,1) x3,y3 ]
[ (4,1) x4,y4 ]
[ (5,1) x5,y5 ]
[ (6,1) x6,y6 ]
[ (7,1) x7,y7 ]
[ (8,1) x8,y8 ]

DEBUG 2017-04-14 06:53:11,628 connectionpool 27334 139762766374656 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:53:53,058 connectionpool 27334 139762766374656 https://api.plot.ly:443 "POST /v2/images HTTP/1.1" 504 211 ('https', 'api.plot.ly', 443, 'POST', '/v2/images', 'HTTP/1.1', 504, 211) null
Traceback (most recent call last):
  File "daily_analysis_report.py", line 132, in <module>
    main()
  File "daily_analysis_report.py", line 111, in main
    subplot_chart = pcharts.analytics_subplot_line(past_days_metrics, plot_titles, subplot_title)
  File "/home/soham/rest_api/scripts/plotly_charts/charts.py", line 138, in analytics_subplot_line
    py.image.save_as(fig, filename=file_path)
  File "/home/soham/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 831, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/home/soham/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 744, in get
    response = v2.images.create(payload)
  File "/home/soham/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/images.py", line 18, in create
    return request('post', url, json=body)
  File "/home/soham/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/utils.py", line 153, in request
    validate_response(response)
  File "/home/soham/rest_api/nvenv/local/lib/python2.7/site-packages/plotly/api/v2/utils.py", line 79, in validate_response
    raise exceptions.PlotlyRequestError(message, status_code, content)
plotly.exceptions.PlotlyRequestError: Image Service Timeout: The image rendering service took too long.

```

Then I run same script again and It was successfully. see below is my debug log.

```
DEBUG 2017-04-14 06:54:22,556 connectionpool 27390 140567683389184 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:54:24,198 connectionpool 27390 140567683389184 https://api.plot.ly:443 "GET /v2/users/current HTTP/1.1" 200 477 ('https', 'api.plot.ly', 443, 'GET', '/v2/users/current', 'HTTP/1.1', 200, 477) null
{u'sharing': u'public', u'world_readable': True, u'plotly_streaming_domain': u'stream.plot.ly', u'plotly_ssl_verification': True, u'plotly_proxy_authorization': False, u'plotly_api_domain': u'https://api.plot.ly', u'auto_open': True, u'plotly_domain': u'https://plot.ly'}
DEBUG 2017-04-14 06:54:24,259 connectionpool 27390 140567683389184 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:54:31,527 connectionpool 27390 140567683389184 https://api.plot.ly:443 "POST /v2/images HTTP/1.1" 200 None ('https', 'api.plot.ly', 443, 'POST', '/v2/images', 'HTTP/1.1', 200, None) null
This is the format of your plot grid:
[ (1,1) x1,y1 ]
[ (2,1) x2,y2 ]
[ (3,1) x3,y3 ]
[ (4,1) x4,y4 ]
[ (5,1) x5,y5 ]
[ (6,1) x6,y6 ]
[ (7,1) x7,y7 ]
[ (8,1) x8,y8 ]

DEBUG 2017-04-14 06:54:31,596 connectionpool 27390 140567683389184 Starting new HTTPS connection (1): api.plot.ly (1, 'api.plot.ly') null
DEBUG 2017-04-14 06:54:36,815 connectionpool 27390 140567683389184 https://api.plot.ly:443 "POST /v2/images HTTP/1.1" 200 None ('https', 'api.plot.ly', 443, 'POST', '/v2/images', 'HTTP/1.1', 200, None) null

```

**Comment by sohamnavadiya** [comment]
Are there any steps that I missed out?

**Comment by cldougl** [comment]
Thanks for reporting @sohamnavadiya ! I believe this is an intermittent issue already logged here: https://github.com/plotly/plotly.py/issues/727
(closing as a duplicate please check https://github.com/plotly/plotly.py/issues/727 for updates )
