### ISSUE TITLE
Dictionary initialization problem

### ISSUE THREAD

**Issue by kript0n** [plotly/plotly.py#754]
I just launched the examples of plotting from official documentation and got this error:

`Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 375, in __init__
    d = {key: val for key, val in dict(*args, **kwargs).items()}
TypeError: dict expected at most 1 arguments, got 2

shell returned 1`

Tried it both with python2 and 3.

**Comment by cldougl** [comment]
@kript0n please include a link to the examples that are resulting in this error

**Comment by cldougl** [comment]
closing due to inactivity
