### ISSUE TITLE
plotly aws lambda

### ISSUE THREAD

**Issue by adlerlinhares** [plotly/plotly.py#773]
im facing some trouble trying to make a plot via aws lambda. the code works fine in my pc, but when i upload to lambda, i get this message error:
```
[Errno 2] No such file or directory: SSLError
Traceback (most recent call last):
File "/var/task/morizonofplot.py", line 113, in lambda_handler
opexind.plot_scatter2(y1,y2,x1,'rgb(242,28,4)','rgb(41,213,247)','None','None', yn1, yn2, nome, gx, gy,indicador)
File "/var/task/module/opexind.py", line 196, in plot_scatter2
py.plot(fig, filename = path, auto_open=False)
File "/var/task/plotly/plotly/plotly.py", line 188, in plot
res = _send_to_plotly(figure, **plot_options)
File "/var/task/plotly/plotly/plotly.py", line 666, in _send_to_plotly
r = requests.post(url, data=payload)
File "/var/task/requests/api.py", line 94, in post
return request('post', url, data=data, json=json, **kwargs)
File "/var/task/requests/api.py", line 49, in request
return session.request(method=method, url=url, **kwargs)
File "/var/task/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/var/task/requests/adapters.py", line 420, in send
raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
```

its a simple code and works really fine in my pc so i dont know the meaning of this error.
so here are part of the code:
```

py.sign_in('xxx','xxx')    
opexind.plot_scatter2(y1,y2,x1,"rgb(242,28,4)","rgb(41,213,247)", "None","None", yn1, yn2, nome,legendx,legendy,path)
```
```
def plot_scatter2( vetory , vetory2 ,vetorx,colour,colour2, moude,moude2, nome, nome2, titleu, legendx, legendy, path):
   trace1 = go.Scatter(
    x   = vetorx,
    y   = vetory,
    name= nome,
    mode = moude,
    fill="tozeroy",
    line=dict(
              color=colour
              ))
   trace2 = go.Scatter(
    x   = vetorx,
    y   = vetory2,
    name= nome2,
    mode = moude2,
    fill="tozeroy",
    line=dict(
              color=colour2
              ))
   layout = go.Layout(
    font=dict( size=10),
    paper_bgcolor="rgb(240,241,241)",
    plot_bgcolor="rgb(240,241,241)",
    title=titleu,

    xaxis=dict(
        title = legendx,
        tickfont=dict(
            size=16,
            color='rgb(107, 107, 107)'
        )
    ),
    yaxis=dict(
        title= legendy,
        titlefont=dict(
            size=16,
            color='rgb(107, 107, 107)'
        ),
        tickfont=dict(
            size=16,
            color='rgb(107, 107, 107)'
        )
    ))

   data = [trace1,trace2]
   fig = go.Figure(data=data, layout=layout)
   py.iplot(fig, filename = path)

```

**Comment by jonmmease** [comment]
I'm afraid I'm not going to be able to help you debug through this one. If you're still interested in this, could you use `plotly.offline.plot` instead?  This way there wouldn't be any network connection required to the plot.ly servers.

**Comment by jonmmease** [comment]
Closing due to lack of activity
