### ISSUE TITLE
ids parameter available only for Scatter, else error raised

### ISSUE THREAD

**Issue by ghtmtt** [plotly/plotly.py#804]
Hi,

while reading in the API documentation I saw that the `ids` parameter should be available for pretty most all the plots.
E.g. scatter and box plot:

https://plot.ly/python/reference/#scatter-ids
https://plot.ly/python/reference/#box-ids

But except for Scatter plot, for the other plot types I always get an error when defining the `ids` parameter. This is the error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 17, in <module>
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 377, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 428, in __setitem__
    raise exceptions.PlotlyDictKeyError(self, path)
plotly.exceptions.PlotlyDictKeyError: 'ids' is not allowed in 'box'

Path To Error: ['ids']

Valid attributes for 'box' at path [] under parents []:

    ['boxmean', 'boxpoints', 'fillcolor', 'hoverinfo', 'jitter',
    'legendgroup', 'line', 'marker', 'name', 'opacity', 'orientation',
    'pointpos', 'showlegend', 'stream', 'type', 'uid', 'visible',
    'whiskerwidth', 'x', 'x0', 'xaxis', 'xsrc', 'y', 'y0', 'yaxis', 'ysrc']

Run `<box-object>.help('attribute')` on any of the above.
'<box-object>' is the object at []

```

and this the super small piece of code to running the same example. With the scatter plot I don't have any problem while with box, bar, scatterternary and many other I get always the same error

```python
import plotly
import plotly.graph_objs as go

# plotly version is 2.0.1

# x and y lists
f1 = [1, 3, 3, 1, 2, 2, 2, 2, 3, 3, 1, 3, 3, 3, 3, 2, 3]
f2 = [1046.67, 1315.0, 1418.0, 997.33, 2972.3, 9700.0, 6726.0, 6002.5, 2096.0, 2470.0, 867.0, 2201.7, 1685.6, 2416.7, 1618.3, 2410.0, 2962.0]
# id list
f5 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


# building the trace with the lists 
trace1 = [go.Box(
x = f1,
y = f2,
ids = f5,
)]

# building the figure and plotting the data
fig = go.Figure(data=trace1)
plotly.offline.plot(fig)



# building the trace with the lists 
trace1 = [go.Scatter(
x = f1,
y = f2,
ids = f5,
mode='markers'
)]

#building the figure and plotting the data
fig = go.Figure(data=trace1)
plotly.offline.plot(fig)
```

**Comment by cldougl** [comment]
Hi there,
You will need an updated version of the plotly.js library for ids to be valid in other chart types.
You can upgrade your plotly.py version with `pip install plotly --upgrade` (latest version is 2.0.12 https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#2012---2017-06-30)
or use `plotly.plotly.plot()` (online rather than offline)

**Comment by ghtmtt** [comment]
Hi,

ups.. I lost the last update.. exactly what I needed ;) 

Thanks!
