### ISSUE TITLE
AttributeError: 'CompositeGenericTransform' object has no attribute 'contains_branch'

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#98]
from matplotlib version 1.1.1

```
Traceback (most recent call last):
File "/Users/wdickerson/Desktop/plotly_test.py", line 14, in <module>
plot_url = py.plot_mpl(fig, filename='mpl-line-style')
File "/Library/Python/2.7/site-packages/plotly/plotly/plotly.py", line 262, in plot_mpl
fig = tools.mpl_to_plotly(fig, resize=resize, strip_style=strip_style)
File "/Library/Python/2.7/site-packages/plotly/tools.py", line 345, in mpl_to_plotly
matplotlylib.Exporter(renderer).run(fig)
File "/Library/Python/2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 49, in run
self.crawl_fig(fig)
File "/Library/Python/2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 116, in crawl_fig
self.crawl_ax(ax)
File "/Library/Python/2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 123, in crawl_ax
self.draw_line(ax, line)
File "/Library/Python/2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 182, in draw_line
force_trans=force_trans)
File "/Library/Python/2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 96, in process_transform
if transform.contains_branch(trans):
AttributeError: 'CompositeGenericTransform' object has no attribute 'contains_branch'
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
