### ISSUE TITLE
`box` value for Violin plot not available

### ISSUE THREAD

**Issue by ghtmtt** [plotly/plotly.py#981]
Hi the `box` parameter is not handled correctly. Trying to run the example of the website in a python console with plotly 2.5 installed leads to the following error (the example code is pasted after the error):

```python
raceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/plotly/tools.py", line 1454, in return_figure_from_figure_or_data
    graph_objs.Figure(figure)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 1174, in __init__
    super(Figure, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 377, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 432, in __setitem__
    value = self._value_to_graph_object(key, value, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 543, in _value_to_graph_object
    _parent=self, _parent_key=key)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 793, in create
    return globals()[class_name](*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 158, in __init__
    value = self._value_to_graph_object(index, value, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 1076, in _value_to_graph_object
    _parent_key=index, **value)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 799, in create
    return PlotlyDict(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 377, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 432, in __setitem__
    value = self._value_to_graph_object(key, value, _raise=_raise)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 543, in _value_to_graph_object
    _parent=self, _parent_key=key)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 799, in create
    return PlotlyDict(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 372, in __init__
    self['type'] = self._name
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 428, in __setitem__
    raise exceptions.PlotlyDictKeyError(self, path)
plotly.exceptions.PlotlyDictKeyError: 'type' is not allowed in 'box'

Path To Error: ['data'][0]['box']['type']

Valid attributes for 'box' at path ['data'][0]['box'] under parents ['figure', 'data', 'violin']:

    []

Run `<box-object>.help('attribute')` on any of the above.
'<box-object>' is the object at ['data'][0]['box']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 26, in <module>
  File "/usr/local/lib/python3.5/dist-packages/plotly/offline/offline.py", line 469, in plot
    '100%', '100%', global_requirejs=False)
  File "/usr/local/lib/python3.5/dist-packages/plotly/offline/offline.py", line 161, in _plot_html
    figure_or_data, validate
  File "/usr/local/lib/python3.5/dist-packages/plotly/tools.py", line 1464, in return_figure_from_figure_or_data
    "".format(err))
plotly.exceptions.PlotlyError: Invalid 'figure_or_data' argument. Plotly will not be able to properly parse the resulting JSON. If you want to send this 'figure_or_data' to Plotly anyway (not recommended), you can set 'validate=False' as a plot option.
Here's why you're seeing this error:

'type' is not allowed in 'box'

Path To Error: ['data'][0]['box']['type']

Valid attributes for 'box' at path ['data'][0]['box'] under parents ['figure', 'data', 'violin']:

    []

Run `<box-object>.help('attribute')` on any of the above.
'<box-object>' is the object at ['data'][0]['box']
```

Plot code:
```python
import plotly
import plotly.graph_objs as go

f2 = [6.81, 6.78, 6.49, 6.72, 6.88, 7.68, 7.69, 7.38, 6.76, 6.84, 6.91, 6.74, 6.77, 6.73, 6.68, 6.94, 6.72]


fig = {
    "data": [{
        "type": 'violin',
        "y": f2,
        "box": {
            "visible": True
        },
        "line": {
            "color": 'black'
        },
        "meanline": {
            "visible": True
        },
        "fillcolor": '#8dd3c7',
        "opacity": 0.6,
        "x0": 'Total Bill'
    }],
    "layout" : {
        "title": "",
        "yaxis": {
            "zeroline": False,
        }
    }
}

plotly.offline.plot(fig)
```

**Comment by rysktky** [comment]
hi, 
i just found, as the error message says,  samples at the official site here is also using "validate = False" .
it seems we need that option?

ref:
https://plot.ly/python/violin/

option usage:
plotly.offline.plot(fig,validate=False)


i am not sure if it is really a bug or expected, 
but are you able to get an expected result with the option?

**Comment by empet** [comment]
@rosswait  With the last plotly version (`pip install plotly==3.0.0.rc11`) the violin plot works properly:
[https://plot.ly/~empet/14908](https://plot.ly/~empet/14908)

**Comment by empet** [comment]
@rosswait  A few minutes ago the  version plotly 3.0.0 was released:
`pip install plotly --upgrade`
